### ISSUE TITLE
SCHEDULED_DEPARTURE not working

### ISSUE THREAD

**Issue by macray76** [zabuldon/teslajsonpy#358]
Using the following service call but the schedule isn't updating. Trace shows it has executed correctly. 

```
service: tesla_custom.api
data:
  command: SCHEDULED_DEPARTURE
  parameters:
    path_vars:
      vehicle_id: "{{ state_attr('binary_sensor.<vehicle>_online', 'id') }}"
    enable: true
    preconditioning_enabled: true
```

Format works for other commands. Using the latest 2022.10.5
